### ISSUE TITLE
Where i can get model checkpoints and tokenizer when executing

### ISSUE THREAD

**Issue by mursaleen5336** [y0mingzhang/prompt-extraction#1]
!python src/llama-chat-prompt-extraction.py --model llama-2 --data sharegpt --attack attacks/generated.json

**Comment by y0mingzhang** [comment]
Please follow steps to download Llama 2 weights [at this link](https://ai.meta.com/blog/5-steps-to-getting-started-with-llama-2/).

**Comment by y0mingzhang** [comment]
closing this issue
